# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# ---------------------------------
# Conexão Mysql
# ----------------------------------
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: PROJETO_JOBS_development
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: PROJETO_JOBS_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: PROJETO_JOBS_production
  pool: 5
  username: root
  password: root
  host: localhost